package au.com.ds.ef;

/**
 * 
 * @author P.Pretki
 *
 */
public enum EventType 
{
    EVENT_TRIGGER, ANY_EVENT_TRIGGER, STATE_ENTER, ANY_STATE_ENTER, STATE_LEAVE, ANY_STATE_LEAVE, STATE_ACTIVATE, ANY_STATE_ACTIVATE, STATE_DEACTIVATE, ANY_STATE_DEACTIVATE, FINAL_STATE, ERROR

}
